# -*- coding: utf-8 -*-


"""
Django settings for pt_shelves project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import djcelery
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^&@rpuvt(sc!afs*_7k%v&-rgk8sz*2_oav+(&hl_x6189*eo%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djcelery',
    'common',
    # 'celery',
    'flow',
    'phone_fee',
    'main',
    'wallet',
    'pt_card',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

AUTHENTICATION_BACKENDS = (
    'common.myuserbackend.MyRemoteUserBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'pt_shelves.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pt_shelves.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASE_TYPE = 2
#正式
if DATABASE_TYPE ==1:
    DEBUG = False
    CARD_ID = 1
    MY_HOST = ''
    MY_URL = 'official'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_report',
            'USER': 'pt_op',
            'PASSWORD': 'PutaoDb2015',
            'HOST': 'rds2seb3yiymjlg8gumzv.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'phone_fee': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'pt_db',
            'PASSWORD': 'pt20120128',
            'HOST': 'sp505adcda1564f.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'flow': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'pt_db',
            'PASSWORD': 'pt20120128',
            'HOST': 'sp505adcda1564f.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'main': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'pt_db',
            'PASSWORD': 'pt20120128',
            'HOST': 'sp505adcda1564f.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'auth_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_auth_admin',
            'USER': 'pt_op',
            'PASSWORD': 'PutaoDb2015',
            'HOST': 'rds2seb3yiymjlg8gumzv.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'cms_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_cms_db',
            'USER': 'pt_cms',
            'PASSWORD': 'cms2015',
            'HOST': 'rds2seb3yiymjlg8gumzv.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'common': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_report',
            'USER': 'pt_op',
            'PASSWORD': 'PutaoDb2015',
            'HOST': 'rds2seb3yiymjlg8gumzv.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'open': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_open',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
            'ATOMIC_REQUESTS': True
        },

    }
#本地
elif DATABASE_TYPE == 2:
    DEBUG = True
    CARD_ID = 3
    MY_HOST = 'test.'
    MY_URL = 'local'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_report',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'phone_fee': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'flow': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'main': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'auth_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_auth_admin',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'cms_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_cms_db_test',
            'USER': 'pt_dev_test',
            'PASSWORD': 'pt_dev_test',
            'HOST': 'rds2seb3yiymjlg8gumzv.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        # 'cms_db': {
        #     'ENGINE': 'django.db.backends.mysql',
        #     'NAME': 'pt_cms_db',
        #     'USER': 'root',
        #     'PASSWORD': 'putao1234',
        #     'HOST': '120.26.214.19',
        #     'PORT': '',
        # },
        'common': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_report',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'pt_card': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_vip',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'open': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_open',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
            'ATOMIC_REQUESTS': True
        },

    }
elif DATABASE_TYPE == 3:
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_report',
            'USER': 'pt_op',
            'PASSWORD': 'PutaoDb2015',
            'HOST': 'rds2seb3yiymjlg8gumzv.mysql.rds.aliyuncs.com',
            'PORT': '',
        },
        'phone_fee': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'flow': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'main': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_db',
            'USER': 'root',
            'PASSWORD': 'putao1234',
            'HOST': '120.26.214.19',
            'PORT': '',
        },
        'auth_db': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_auth_admin',
            'USER': 'root',
            'PASSWORD': '123456',
            'HOST': '127.0.0.1',
            'PORT': '',
        },
        'common': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pt_biz_report',
            'USER': 'pt_op',
            'PASSWORD': 'PutaoDb2015',
            'HOST': 'rds2seb3yiymjlg8gumzv.mysql.rds.aliyuncs.com',
            'PORT': '',
        },

    }
#测试
else:
    DEBUG = True
    DATABASES = {

    }



DATABASE_ROUTERS = ['pt_shelves.dbsettings.AuthRouter']


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE='Asia/Shanghai'


USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = [
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../'), 'static/'),
]


# djcelery 配置
djcelery.setup_loader()
BROKER_URL = 'redis://localhost:6379/3'
CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERYD_CONCURRENCY = 8
CELERY_EVENT_QUEUE_TTL = 30
CELERY_SEND_TASK_ERROR_EMAILS = False
CELERY_IGNORE_RESULT = True
