# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtDaojiaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('goodsid', models.BigIntegerField(blank=True, db_column='goodsId', null=True)),
                ('cpgoodsid', models.CharField(blank=True, db_column='cpGoodsId', max_length=64)),
                ('order_no', models.CharField(max_length=50)),
                ('cporderno', models.CharField(blank=True, db_column='cpOrderNo', max_length=100)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('providermobile', models.CharField(blank=True, db_column='providerMobile', max_length=16)),
                ('payway', models.IntegerField(db_column='payWay')),
                ('service_time', models.DateTimeField()),
                ('service_length', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=32)),
                ('area', models.CharField(blank=True, max_length=32)),
                ('service_address', models.CharField(max_length=256)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('staffid', models.CharField(blank=True, db_column='staffId', max_length=100)),
                ('staffname', models.CharField(blank=True, db_column='staffName', max_length=32)),
                ('staffphone', models.CharField(blank=True, db_column='staffPhone', max_length=16)),
                ('staffheadurl', models.CharField(blank=True, db_column='staffHeadUrl', max_length=512)),
                ('consumer', models.CharField(max_length=32)),
                ('consumermobile', models.CharField(db_column='consumerMobile', max_length=16)),
                ('pt_username', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1024)),
                ('pay_price', models.BigIntegerField()),
                ('create_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('appid', models.BigIntegerField(db_column='appId')),
                ('goodsname', models.CharField(blank=True, db_column='goodsName', max_length=64)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('cancel_by', models.IntegerField(blank=True, null=True)),
                ('cancel_msg', models.CharField(blank=True, max_length=512)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('simple_address', models.CharField(blank=True, max_length=128)),
                ('service_type', models.IntegerField(blank=True, null=True)),
                ('extrainfo', models.CharField(blank=True, db_column='extraInfo', max_length=256)),
                ('sku', models.CharField(blank=True, max_length=256)),
                ('staff_sex', models.IntegerField(blank=True, null=True)),
                ('promotion_activity_info', models.CharField(blank=True, max_length=1024)),
                ('goodscustomizeorderinfo', models.CharField(blank=True, db_column='goodsCustomizeOrderInfo', max_length=1024)),
                ('is_later_pay_order', models.IntegerField()),
                ('status_desc', models.CharField(blank=True, max_length=255)),
                ('pay_status', models.IntegerField()),
                ('set_price_time', models.DateTimeField(blank=True, null=True)),
                ('pt_u_id', models.CharField(blank=True, max_length=50)),
                ('goodsicon', models.CharField(blank=True, db_column='goodsIcon', max_length=512)),
                ('source_channel', models.IntegerField(blank=True, null=True)),
                ('pt_comment', models.CharField(blank=True, max_length=256)),
                ('attr_160314', models.CharField(blank=True, max_length=1024)),
                ('is_shopping_car', models.IntegerField(blank=True, null=True)),
                ('is_shopping_car_goods', models.IntegerField(blank=True, null=True)),
                ('user_sex', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
