# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161107_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('pid', models.CharField(max_length=10)),
                ('command', models.CharField(max_length=200)),
                ('fileServer', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PtDaojiaOrder',
        ),
    ]
