# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161107_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server_Service',
            new_name='ServerService',
        ),
    ]
